package com.nc.tools.ui.components.models.templates;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;

/**
 *
 * @author vpandhar
 */
public class ListValueTemplate extends javax.swing.JPanel {

    private UIIcon icon;    
    private boolean hideKey;
        
    
    public ListValueTemplate(Image image, boolean hide) {
        hideKey = hide;        
        icon = new UIIcon(image, 20, 20);
        initComponents();        
        addComponents();  
        
    }
    
    private void addComponents(){
        add(icon);
        if(!hideKey) add(keyLabel);
        add(valueLabel);        
        setOpaque(true);
    }
    
    public void setKeyFontAndColor(Font font, Color color){
        keyLabel.setFont(font);
        keyLabel.setForeground(color);        
    }
    
    public void highLightText(Color fgColor, Color bgColor){
        keyLabel.setOpaque(true);
        keyLabel.setForeground(fgColor);
        keyLabel.setBackground(bgColor);        
    }
   
    public void setValueFontAndColor(Font font, Color color){
        valueLabel.setFont(font);
        valueLabel.setForeground(color);
    }
   
    public void setBackgroundColor(Color color){                       
        setBackground(color);
    }
    
    public void setProperties(String keyTxt, String valueTxt){
        keyLabel.setText(keyTxt);
        valueLabel.setText(valueTxt);       
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keyLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        keyLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        keyLabel.setText("Sample Key");
        keyLabel.setPreferredSize(null);

        valueLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        valueLabel.setText("Sample Value");

        setOpaque(false);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 2));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel keyLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
