package com.nc.tools.ui.components.ui;

import com.nc.tools.ui.components.models.UIComboboxValue;
import com.nc.tools.ui.components.renderers.UICoboboxRenderer;
import java.awt.event.KeyListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.ListCellRenderer;


public class UICombobox extends javax.swing.JPanel {

    private ImageIcon image = new ImageIcon(getClass().getResource("/com/nc/tools/ui/components/resources/console.png")); 
    private final DefaultComboBoxModel<UIComboboxValue> model = new DefaultComboBoxModel<>();  
    
   
    public UICombobox() {
       initComponents();
    }
      
    
    private ListCellRenderer getRenderer() {
        return new UICoboboxRenderer();
    }
    
    public DefaultComboBoxModel populate() {                            
        return model;
    }
    
    public void addElement(String value) {
        model.addElement(new UIComboboxValue(image, value));
    }  
    
    public void clear() {
        model.removeAllElements();
    }
    
    @Override
    public void addKeyListener(KeyListener listener) {
        comboBox.addKeyListener(listener);
    }   
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBox = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        comboBox.setModel(populate());
        comboBox.setRenderer(getRenderer());
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        comboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboBoxKeyReleased(evt);
            }
        });
        add(comboBox, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        
    }//GEN-LAST:event_comboBoxActionPerformed

    private void comboBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBoxKeyReleased
        
    }//GEN-LAST:event_comboBoxKeyReleased
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    // End of variables declaration//GEN-END:variables
}
