/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nc.tools.ui.components.ui.test;

import javax.swing.JLabel;

/**
 *
 * @author vipa0816
 */
public class UIListTest extends javax.swing.JFrame {

    private static int num;
    
    /**
     * Creates new form UIListTest
     */
    public UIListTest() {
        initComponents();
    }
    
    private void addSamples() {
        for(int i = 0; i < 10; i++){
            list.addElement("Mango_" + ++num);
            list.addElement("Apple_" + ++num);
            list.addElement("Grapes_" + ++num);
            list.addElement("Banana_" + ++num);
            list.addElement("Strawberry_" + ++num);
            list.addElement("Blueberry_" + ++num);
            list.addElement("Sapota_" + ++num);
            list.addElement("Water Melon_" + ++num);
            list.addElement("Musk Melon_" + ++num);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemName = new javax.swing.JTextField();
        list = new com.nc.tools.ui.components.ui.UIList();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameActionPerformed(evt);
            }
        });
        getContentPane().add(itemName, java.awt.BorderLayout.PAGE_START);

        list.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        list.setHideKey(true);
        list.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/nc/tools/ui/components/resources/icons8-add-to-favorites-20.png")).getImage());

        javax.swing.GroupLayout listLayout = new javax.swing.GroupLayout(list);
        list.setLayout(listLayout);
        listLayout.setHorizontalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        listLayout.setVerticalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        getContentPane().add(list, java.awt.BorderLayout.CENTER);
        list.init();

        jButton1.setText("Add Samples");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(233, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Thread(()->{
            addSamples();
        }).start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameActionPerformed
        list.addElement(itemName.getText());
        new JLabel();
    }//GEN-LAST:event_itemNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIListTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIListTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIListTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIListTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIListTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField itemName;
    private javax.swing.JButton jButton1;
    private com.nc.tools.ui.components.ui.UIList list;
    // End of variables declaration//GEN-END:variables
}
